GAMES = [
    "Crazy_Cars",
    "Diamond_Dig",
    "Dodge_Balls",
    "Hectic_Highway",
    "I_Spy",
    "Mug_Shot",
    "Repellion",
    "Saving_Face",
    "Sparring_Wario",
    "Super_Wario_Bros",
    "The_Maze_That_Pays",
    "Wario_Wear",
    "Wario_Whirled",
]
