[tool.poetry]
name = "models"
version = "0.1.0"
description = ""
authors = ["Nick Lay <layns@mail.uc.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
black = "^22.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
